site_name: Agin Docs
theme:
  name: "material"
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - content.code.copy
  copyright: ""
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
nav:
  - Home: index.md
  - Classification: classification.md
  - Regression: regression.md
  - Neural Network: neural.md
  - Utils: utils.md
extra:
  generator: false
extra_css:
  - assets/custom.css
